//// <auto-generated />
////
//// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
////
////    using dir2abou.Entities;
////
////    var detailedResult = DetailedResult.FromJson(jsonString);

//namespace dir2abou.Entities
//{
//    using System;
//    using System.Collections.Generic;

//    using System.Globalization;
//    using Newtonsoft.Json;
//    using Newtonsoft.Json.Converters;

//    public partial class DetailedResult
//    {
//        [JsonProperty("Id")]
//        public string Id { get; set; }

//        [JsonProperty("DiaryNumber")]
//        public string DiaryNumber { get; set; }

//        [JsonProperty("DateSubmitted")]
//        public DateTimeOffset DateSubmitted { get; set; }

//        [JsonProperty("Ombudsman")]
//        public string Ombudsman { get; set; }

//        [JsonProperty("SentInAs")]
//        public string SentInAs { get; set; }

//        [JsonProperty("RequiresMultipleSignatures")]
//        public bool RequiresMultipleSignatures { get; set; }

//        [JsonProperty("Status")]
//        public string Status { get; set; }

//        [JsonProperty("ServiceId")]
//        public string ServiceId { get; set; }

//        [JsonProperty("ServiceName")]
//        public string ServiceName { get; set; }

//        [JsonProperty("ServiceVersion")]
//        public long ServiceVersion { get; set; }

//        [JsonProperty("ServiceStatuses")]
//        public List<string> ServiceStatuses { get; set; }

//        [JsonProperty("Citizens")]
//        public List<Citizen> Citizens { get; set; }

//        [JsonProperty("Signatures")]
//        public List<Signature> Signatures { get; set; }

//        [JsonProperty("Payments")]
//        public List<object> Payments { get; set; }

//        [JsonProperty("QueueItems")]
//        public List<object> QueueItems { get; set; }

//        [JsonProperty("Fields")]
//        public List<Field> Fields { get; set; }

//        [JsonProperty("Attachments")]
//        public List<Attachment> Attachments { get; set; }

//        [JsonProperty("DynamicAttachments")]
//        public List<Attachment> DynamicAttachments { get; set; }
//    }

//    public partial class Attachment
//    {
//        [JsonProperty("Id")]
//        public long Id { get; set; }

//        [JsonProperty("Type")]
//        public string Type { get; set; }

//        [JsonProperty("FileName")]
//        public string FileName { get; set; }

//        [JsonProperty("SystemFileName")]
//        public string SystemFileName { get; set; }

//        [JsonProperty("FileType")]
//        public string FileType { get; set; }

//        [JsonProperty("FileDescription")]
//        public string FileDescription { get; set; }

//        [JsonProperty("FileDefinition")]
//        public object FileDefinition { get; set; }

//        [JsonProperty("DateUploaded")]
//        public DateTimeOffset DateUploaded { get; set; }

//        [JsonProperty("FileSize")]
//        public long FileSize { get; set; }

//        [JsonProperty("Content")]
//        public string Content { get; set; }

//        [JsonProperty("FieldId")]
//        public string FieldId { get; set; }

//        [JsonProperty("Arguments")]
//        public List<object> Arguments { get; set; }
//    }

//    public partial class Citizen
//    {
//        [JsonProperty("HasSigned")]
//        public bool HasSigned { get; set; }

//        [JsonProperty("IsCoApplicant")]
//        public bool IsCoApplicant { get; set; }

//        [JsonProperty("UserIdentity")]
//        public string UserIdentity { get; set; }

//        [JsonProperty("FirstName")]
//        public string FirstName { get; set; }

//        [JsonProperty("LastName")]
//        public string LastName { get; set; }

//        [JsonProperty("StreetAddress")]
//        public string StreetAddress { get; set; }

//        [JsonProperty("PostalCode")]
//        public string PostalCode { get; set; }

//        [JsonProperty("City")]
//        public string City { get; set; }

//        [JsonProperty("AltStreetAddress")]
//        public string AltStreetAddress { get; set; }

//        [JsonProperty("AltPostalCode")]
//        public string AltPostalCode { get; set; }

//        [JsonProperty("AltCity")]
//        public string AltCity { get; set; }

//        [JsonProperty("Email")]
//        public string Email { get; set; }

//        [JsonProperty("HomePhone")]
//        public string HomePhone { get; set; }

//        [JsonProperty("MobilePhone")]
//        public string MobilePhone { get; set; }

//        [JsonProperty("MunicipalityCode")]
//        public string MunicipalityCode { get; set; }

//        [JsonProperty("BirthPlaceCountyCode")]
//        public string BirthPlaceCountyCode { get; set; }

//        [JsonProperty("BirthPlaceCommunity")]
//        public string BirthPlaceCommunity { get; set; }

//        [JsonProperty("BirthPlaceOverSeaCity")]
//        public string BirthPlaceOverSeaCity { get; set; }

//        [JsonProperty("BirthPlaceOverSeaCountry")]
//        public string BirthPlaceOverSeaCountry { get; set; }

//        [JsonProperty("MaritalStatusCode")]
//        public string MaritalStatusCode { get; set; }

//        [JsonProperty("HasProtectedIdentity")]
//        public bool HasProtectedIdentity { get; set; }
//    }

//    public partial class Field
//    {
//        [JsonProperty("Question")]
//        public Answer Question { get; set; }

//        [JsonProperty("Answer")]
//        public Answer Answer { get; set; }
//    }

//    public partial class Answer
//    {
//        [JsonProperty("#cdata-section")]
//        public string CdataSection { get; set; }
//    }

//    public partial class Signature
//    {
//        [JsonProperty("Date")]
//        public DateTimeOffset Date { get; set; }

//        [JsonProperty("SignatureData")]
//        public string SignatureData { get; set; }

//        [JsonProperty("Issuer")]
//        public string Issuer { get; set; }

//        [JsonProperty("UserIdentity")]
//        public string UserIdentity { get; set; }
//    }

   

//    public static class SerializeDetailedResult
//    {
//        public static string ToJson(this DetailedResult self) => JsonConvert.SerializeObject(self, dir2abou.Entities.Converter.Settings);
//    }

//    internal static class Converter
//    {
//        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
//        {
//            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
//            DateParseHandling = DateParseHandling.None,
//            Converters =
//            {
//                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
//            },
//        };
//    }
//}
